package org.c4marathon.assignment.domain;

public enum OrderStatus {
	ORDERED_PENDING,
	ORDERED_ACCEPTED,
	ORDERED_SENT,
	ORDERED_SHIPPED,
	CUSTOMER_ACCEPTED,
	REFUND_REQUESTED_BY_CUSTOMER,
	REFUND_REQUESTED_BY_SELLER,
	REFUND_ACCEPTED,
	REFUND_IN_PROGRESS,
	REFUND_COMPLETED
}
