spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/Accelerated To-Do?serverTimezone=Asia/Seoul
    username: root
    password: hyhy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        default_batch_fetch_size: 1000
  logging:
    level:
      org.hibernate:
        SQL: debug
        type:
          descriptor.sql: trace