spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      max-lifetime: 60000
      connection-timeout: 30000
      maximum-pool-size: 10
    url: jdbc:mysql://localhost:3306/community?rewriteBatchedStatements=true

  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.c4marathon.assignment.global.error: debug