# default
server:
  port: 8000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  # Redis
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

        transaction:
          interceptor:

