# default
server:
  port: 8000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  #Redis
  data:
    redis:
      host: ${redis.host}
      password: ${redis.password}
      port: ${redis.port}

  #Mongo
  mongo:
    host: ${mongo.host}
    port: ${mongo.port}
    database: ${mongo.database}
    username: ${mongo.username}
    password: ${mongo.password}


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

        transaction:
          interceptor:

bank-account:
  deposit:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 10
    complete-on-shutdown: true

redis-stream:
  stream-key: send-stream
  consumer-group-name: send-group
  consumer-name: send-consumer
  claim-consumer-name: claim-consumer
  pending-time: 3000
  is-test: false
