# default
server:
  port: 8000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.devUrl}
    username: ${mysql.devUsername}
    password: ${mysql.devPassword}

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

        transaction:
          interceptor:

