spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_ID}
    password: ${DB_USER_PASSWORD}
    hikari:
      connection-timeout: 5000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_ID}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000